server:
  port: 8091
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
spring:
  datasource:
    url: jdbc:mysql://118.24.214.42:3306/cst?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: k59360
    driver-class-name: com.mysql.cj.jdbc.Driver
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.3.5
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller

mybatis:
  type-aliases-package: com.github.novicezk.midjourney.domain
  mapper-locations: classpath*:mapper/*.xml
